// revenue-hero-angular-demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'revenue-hero-angular-demo';


  handleButtonClick() {
    const hero = new window.RevenueHero({ routerId: '590' });

    hero
      .submit({ email: "example@example.com", noOfEmployees: "50-100" })
      .then((data) => {
        hero.dialog.open(data);
      })
      .catch((error) => {
        console.log(error);
      });
  }


}

<script type="text/javascript" src="https://app.revenuehero.io/scheduler.min.js"></script>
<div>
  <!-- Your Angular component content -->
  <button id="buttonId" (click)="handleButtonClick()">Book Meeting</button>
</div>

// revenue-heror-react-demo/src/App.js
import React, { useEffect } from "react";

const App = () => {
  useEffect(() => {
    const script1 = document.createElement("script");
    script1.src = "https://app.revenuehero.io/scheduler.min.js";
    script1.async = true;
    script1.defer = true;
    document.body.appendChild(script1);
    return () => {
      document.body.removeChild(script1);
    };
  }, []);

  const handleButtonClick = () => {
    const hero = new window.RevenueHero({
      routerId: "590",
    });

    hero
      .submit({ email: "sample@example.com", noOfEmployees: "50-100" })
      .then((data) => {
        hero.dialog.open(data);
      })
      .catch((error) => {
        console.log(error);
      });
  };

  return (
    <div>
      <button onClick={handleButtonClick}>Book Meeting</button>
    </div>
  );
};

export default App;
